### ISSUE TITLE
Could not set textSize on BootstrapButton via layout.xml

### ISSUE THREAD

**Issue by tmtysk** [Bearded-Hen/Android-Bootstrap#163]
I could not set textSize on BootstrapButton via layout.xml:

```
<com.beardedhen.androidbootstrap.BootstrapButton
 android:id="@+id/check_button"
 app:fontAwesomeIcon="fa_check_circle"
 app:bootstrapBrand="success"
 android:layout_width="match_parent"
 android:layout_height="match_parent"
 android:layout_weight="1"
 android:textSize="120sp" />
```

but succeeded to set it via application source code:

```
check_button.setTextSize(120.0f)
```

Can I set it via lauout.xml?

**Comment by jamie-beardedhen** [comment]
The textsize of BootstrapButton is set via its bootstrapSize attribute, so this is expected behaviour when inflating the view. If you require further customisation then setting the text size programatically is the correct approach.

See: https://github.com/Bearded-Hen/Android-Bootstrap/wiki/Bootstrap-Button
