### ISSUE TITLE
Upgrading AwesomeFont to version 4.7

### ISSUE THREAD

**Issue by bho20** [Bearded-Hen/Android-Bootstrap#194]
Hi team,

FontAwesome has been upgraded to version 4.7 Please help me to upgrade to the new version. Currently, we are using version 4.5

Thanks,

**Comment by bho20** [comment]
Hello Jamie, can you help me soon?

**Comment by jamie-beardedhen** [comment]
All that needs to be done here is to update FontAwesome.java to include the icons added since 4.5, and to update the font asset: https://github.com/Bearded-Hen/Android-Bootstrap/blob/master/AndroidBootstrap/src/main/java/com/beardedhen/androidbootstrap/font/FontAwesome.java

Pull requests are welcome on this as I don't currently have the time to implement the fix myself
