### ISSUE TITLE
Error inflating class com.beardedhen.androidbootstrap.BootstrapButton

### ISSUE THREAD

**Issue by vanlaodev** [Bearded-Hen/Android-Bootstrap#74]
It seems like BootstrapButton try to get textSize after TypeAdapter recycled cause error "Cannot make calls to a recycled instance!".

Related code snippets in BootstrapButton:

``` java
finally {
  a.recycle();
}

// blablabla

if (a.getString(R.styleable.BootstrapButton_android_textSize) == null) {
  fontSize = bootstrapSize.getFontSize();
}
```

**Comment by marcbiaggini** [comment]
Fix it ! 
Since December 3rd, 2014, build tools 1.0.0-rc1 was released. Now, all you need to do is override this:

1) Modify your build.gradle like so:

android {
    compileSdkVersion 22
    buildToolsVersion "23.0.0"

         defaultConfig {
             minSdkVersion 14 //lower than 14 doesn't support multidex
             targetSdkVersion 22

             // Enabling multidex support.
             multiDexEnabled true
         }
}

dependencies {
    compile 'com.android.support:multidex:1.0.1'
}

2) Also you must change your manifest file. 
<application
       ...
       android:name="android.support.multidex.MultiDexApplication">
       ...
   </application>

Sources
https://developer.android.com/tools/building/multidex.html
http://blog.osom.info/2014/10/multi-dex-to-rescue-from-infamous-65536.html
